name: ESSD-DRN
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - R=4.1.0
  - pyarrow
  - keras>=2.4.3
  - tensorflow>=2.3.0
  - numpy
  - matplotlib
  - xarray
  - dask
  - netcdf4
  - h5netcdf
